### Ruta principal
GET http://localhost:3008/

### Ruta para obtener todos los productos
GET http://localhost:3008/productos

### Ruta para obtener un producto por su ID
GET http://localhost:3008/productos/id/6675f18850635bfaa44b8b0f

### Filtrar productos por nombre (búsqueda parcial)
GET http://localhost:3008/productos/nombre/si

### Agregar un nuevo producto 
POST http://localhost:3008/productos
Content-Type: application/json

{
  "nombre": "Mesa de luz",
  "precio": 250000,
  "categoria": "Dormitorio"
}

### Modificar el precio de  un producto parcialmente (PATCH)
PATCH http://localhost:3008/productos/66965d46af9d17f541ce5ba0
Content-type: application/json

{
  "precio": "7757"
}

### Modificar un producto completamente (PUT)
PUT http://localhost:3008/productos/66965d46af9d17f541ce5ba0
Content-type: application/json

{
  "codigo": 35,
  "nombre": "Sillon Gamer TZ-011",
  "precio": 355000,
  "categoria": "Sala de computacion"
}


### Eliminar un producto por su ID
DELETE http://localhost:3008/productos/eliminar/669679de81493a4454ad22cc


### Rutas ADICIONALES
### Ruta para registrar a un usuario
POST http://localhost:3008/registro
Content-Type: application/json

{
        "usuario": "Matias",
        "contraseña": "1234567",
        "email": "matu@gmail.com"
}

### Ruta para logear a un usuario
POST http://localhost:3008/login
Content-Type: application/json

{
        "usuario": "Pedro Gonzalez",
        "contraseña": "A3CVFN1"
}

### Ruta protegida
GET http://localhost:3008/perfil

### Cerrar session
POST http://localhost:3008/logout